DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (id INT, CUSTOMER_NAME VARCHAR(255), GENDER VARCHAR(255), CITY VARCHAR(255));

INSERT INTO CUSTOMER VALUES(1,'Gopal','Male','Chennai');
INSERT INTO CUSTOMER VALUES(2,'Dipak','Male','Kolkata');
INSERT INTO CUSTOMER VALUES(3,'Vinayak','Male','Rajasthan');
INSERT INTO CUSTOMER VALUES(4,'Lakshmi','Female','Hyderabad');